### ISSUE TITLE
Cordova android build error after upgrading to v1.0rc2

### ISSUE THREAD

**Issue by virtser** [chrisben/imgcache.js#155]
Cause by "chrisben:imgcache" folder in the repo.

*/Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/assets/armv7/debug/www/bower_components/imgcache.js/chrisben:imgcache: error: Invalid directory name, unable to add.*

```
generateArmv7DebugResources
:mergeArmv7DebugResources
:processArmv7DebugManifest
:processArmv7DebugResources
/Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/assets/armv7/debug/www/bower_components/imgcache.js/chrisben:imgcache: error: Invalid directory name, unable to add.
:processArmv7DebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/dvirtser/AndroidSDK/android-sdk-macosx/build-tools/22.0.1/aapt package -f --no-crunch -I /Users/dvirtser/AndroidSDK/android-sdk-macosx/platforms/android-22/android.jar -M /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/manifests/full/armv7/debug/AndroidManifest.xml -S /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/res/armv7/debug -A /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/assets/armv7/debug -m -J /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/generated/source/r/armv7/debug -F /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/res/resources-armv7-debug.ap_ --debug-mode --custom-package com.notifaya.prod -0 apk --output-text-symbols /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/symbols/armv7/debug
  Error Code:
  	1
  Output:
  	/Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build/intermediates/assets/armv7/debug/www/bower_components/imgcache.js/chrisben:imgcache: error: Invalid directory name, unable to add.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.454 secs

/Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Users/dvirtser/projects/notifaya/mobile/phonegap/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by chrisben** [comment]
I don't know why you got this folder name. How did you install this library?
I've just tried to install it using bower and I don't get this subfolder name.
```
bower install imgcache.js
```

**Comment by chrisben** [comment]
Ok I see now, this folder had been created for Meteor users. 
I will try to find a way to avoid this folder name.

**Comment by chrisben** [comment]
There were 2 pull requests to fix this. This will be part of 1.0.0 that I plan to release today.
